### PR TITLE
Update to LLVM 11.0.

### PR DESCRIPTION
**Pull request by sunfishcode**
LLVM 11 is [now released](https://github.com/llvm/llvm-project/releases/tag/llvmorg-11.0.0).

cc https://github.com/WebAssembly/wasi-sdk/issues/154

### CODE REVIEW

**Comment by sbc100** [comment]
Wow.. not wasting in time there!

**Review by sbc100 — APPROVED** [review]

**Comment by TerrorJack** [comment]
Will there be a recent `wasi-sdk` release with LLVM 11? :)

**Comment by sbc100** [comment]
If you want I believe you can get the binaries from the CI of this PR:  https://github.com/WebAssembly/wasi-sdk/pull/158/checks.  

But yes we should tag a release ASAP I guess.

**Comment by sunfishcode** [comment]
The release is now tagged: https://github.com/WebAssembly/wasi-sdk/releases/tag/wasi-sdk-12

**Pull request merged**
