### PR TITLE
Use standardized `CC`, `AR`, `NM` env vars

### PR DESCRIPTION
**Pull request by Ericson2314**
Companion to https://github.com/WebAssembly/wasi-libc/pull/275

### CODE REVIEW

**Comment by Ericson2314** [comment]
OK https://github.com/WebAssembly/wasi-libc/pull/275 is merged, so I updated the submodule here as promised. If @sunfishcode you want to approve CI, it should hopefully work.

**Comment by sunfishcode** [comment]
It looks like the ubuntu and macos builds succeeded, but the windows build is getting an error:
> CMake Error at C:/Program Files/CMake/share/cmake-3.23/Modules/CMakeDetermineCCompiler.cmake:49 (message):
  Could not find compiler set in environment variable CC:
>
>  cl.

**Comment by Ericson2314** [comment]
@sunfishcode That looks like an existing issue, see the top of `main`'s CI results: https://github.com/WebAssembly/wasi-sdk/runs/5727959507?check_suite_focus=true

It does look like that error is analogously caused by an inconvenience `CC` set in the ambient environment, but actually `CC=cl` is explicit in the YAML.

I was going to take a stab at fixing that in a separate PR under the assumption it was the the same sort of thing, but now that I see this is different I am not quite sure what the intent is nor how how to fix it.

**Comment by sunfishcode** [comment]
@lygstate Do you know if the current CI errors on main are related to your recent PRs? If so, could you take a look?

**Comment by lygstate** [comment]
> @lygstate Do you know if the current CI errors on main are related to your recent PRs? If so, could you take a look?

I have create the pr to fix IT， please merge

**Comment by sunfishcode** [comment]
The CI issues are fixed in other PRs, and this looks right to me and fixes an issue I'm seeing, so I'm going ahead and merging this.

**Pull request merged**
