### PR TITLE
[DO NOT MERGE] Stage release 9

### PR DESCRIPTION
**Pull request by pchickey**
This merges #89 #107 #109 on top of master.

I just discovered that Github Actions was not enabled when the repo moved to its new home, so the last few PRs were merged without any CI! I have re-enabled it. Hopefully this branch will show we are all clear.

### CODE REVIEW

**Comment by sbc100** [comment]
Any not just land those specific PRs in place?  (or is this PR not for landing, just for experimenting?)

**Comment by pchickey** [comment]
I want to land those specific PRs in place, yes. I should have marked this as not for merging, and have corrected that.

Aside from actually running CI, I want to run some tests locally in lucet with a representative release build, so I'm having Actions build me one rather than get my laptop hot for 2 hours.

**Comment by pchickey** [comment]
Mac CI has failed twice in a row with the exact same `error 2` at the end of the wasi-libc.BUILT target. I can't figure out what the actual failure is that led to this by reading the log. Does anyone else have a clue?

**Comment by sbc100** [comment]
I really wish github would hurry up and add my favorite feature of circleci which is "rerun tests with SSH access to bot".. then you can just log into the failing bot and debug directly (including windows!)

**Comment by sbc100** [comment]
Yeah.. it looks like make simply returns 2 for no reported reason.  

Perhaps try without the `-j` flag in case things are appearing out of order?

**Pull request closed without merging**
