### PR TITLE
Update README to use the name "WASI SDK" consistently

### LINKED ISSUE #383: What's the official name of the project?
Is it "WASI SDK" or "WASI-SDK" (i.e. w/ or w/o a hyphen)? The usage is inconsistent in the README.

### PR DESCRIPTION
**Pull request by brettcannon**
Closes #383

### CODE REVIEW

**Review by sunfishcode — APPROVED** [review]
Thanks!

**Comment by hugovk** [comment]
Perhaps also?

```diff
-Use a toolchain file to setup the *wasi-sdk* platform.
+Use a toolchain file to setup the *WASI SDK* platform.
```

**Comment by brettcannon** [comment]
> Perhaps also?
> 
> ```diff
> -Use a toolchain file to setup the *wasi-sdk* platform.
> +Use a toolchain file to setup the *WASI SDK* platform.
> ```

The reason I didn't update that is the next line of text says, "or the wasi-sdk-thread platform", suggesting it's being used as a technical term in that situation rather than a name.

**Comment by brettcannon** [comment]
@sunfishcode the failures look unrelated to the PR.

**Pull request merged**
