### PR TITLE
Bump llvm version to 17.0.4

### PR DESCRIPTION
**Pull request by yamt**

### CODE REVIEW

**Comment by yamt** [comment]
i manually tested the macOS asset.

**Comment by yamt** [comment]
superseded by https://github.com/WebAssembly/wasi-sdk/pull/338

**Comment by sbc100** [comment]
I'd rather see this kind of change land as its own separate PR

**Comment by yamt** [comment]
> I'd rather see this kind of change land as its own separate PR

me too. but i can understand others think differently.

**Pull request closed without merging**
