### PR TITLE
Update wasi-libc to latest HEAD

### PR DESCRIPTION
**Pull request by abrown**
This pulls in a variety of changes, many of them related to enabling threads in wasi-libc. There may be more changes necessary before releasing a prelease version of wasi-sdk that supports the new `wasm32-wasi-threads` target, but this should get the majority of them.

### CODE REVIEW

**Review by sbc100 — APPROVED** [review]

**Comment by abrown** [comment]
@yamt, @loganek, @sbc100, others: any other wasi-libc PRs that you would like to see merged before a wasi-sdk prerelease is created. Here is the list open PRs: https://github.com/WebAssembly/wasi-libc/pulls. My suggestions (at least to discuss--open to rejecting as well): https://github.com/WebAssembly/wasi-libc/pull/324, https://github.com/WebAssembly/wasi-libc/pull/383,

**Comment by loganek** [comment]
@abrown I still think we should merge https://github.com/WebAssembly/wasi-libc/pull/324 (already resolved conflicts) but if anybody have a strong opinion about that, we can continue the discussion and postpone it.

**Comment by abrown** [comment]
Merged https://github.com/WebAssembly/wasi-libc/pull/324; any other opinions on https://github.com/WebAssembly/wasi-libc/pull/383? It's similar in that it is a "enable weird features to support compatibility" change; wasi-libc does not have much to say about priority inheritance but that PR makes it appear as if it works.

**Comment by yamt** [comment]
> any other opinions on [WebAssembly/wasi-libc#383](https://github.com/WebAssembly/wasi-libc/pull/383)? It's similar in that it is an "enable weird features to support compatibility" change; wasi-libc does not have much to say about priority inheritance but that PR makes it appear as if it works.

as i commented in the PR, i feel it isn't ready even as an "just ignore the request saying ok" implementation. let's skip it for the prerelease.

**Comment by abrown** [comment]
Ok, I closed WebAssembly/wasi-libc#383 and updated this PR with the now-merged WebAssembly/wasi-libc#324. After this PR merges, we should be ready for a wasi-sdk + threads prerelease.

**Comment by yamt** [comment]
> This pulls in a variety of changes, many of them related to enabling threads in wasi-libc. There may be more changes necessary before releasing a prelease version of wasi-sdk that supports the new `wasm32-wasi-threads` target, but this should get the majority of them.

do we plan to have a "official" prerelease in https://github.com/WebAssembly/wasi-sdk/releases ?
or at least a tag?

**Pull request merged**
