### PR TITLE
WIP: Re-enable windows build in CI

### PR DESCRIPTION
**Pull request by sbc100**

### CODE REVIEW

**Comment by sbc100** [comment]
Looks like it gets past building llvm and then fails due to many other missing things:

```
#include <stddef.h>
3783
         ^~~~~~~~~~
3784
1 error generated.
3785
In file included from D:/a/wasi-sdk/wasi-sdk/src/wasi-libc/basics/sources/abort.c:1:
3786
In file included from C:/Program Files/Git/opt/wasi-sdk/share/wasi-sysroot/include\stdlib.h:6:
3787
C:/Program Files/Git/opt/wasi-sdk/share/wasi-sysroot/include\__functions_malloc.h:7:10: fatal error: 'stddef.h' file not found
3788
#include <stddef.h>
3789
         ^~~~~~~~~~
3790
1 error generated.
3791
mingw32-make[1]: *** [Makefile:359: D:/a/wasi-sdk/wasi-sdk/src/wasi-libc/build/basics/sources/reallocarray.o] Error 1
3792
mingw32-make[1]: *** Waiting for unfinished jobs....
3793
mingw32-make[1]: *** [Makefile:358: D:/a/wasi-sdk/wasi-sdk/src/wasi-libc/build/basics/sources/abort.o] Error 1
3794
cd "D:/a/wasi-sdk/wasi-sdk/src/wasi-libc/build" && \
3795
"/opt/wasi-sdk/bin/clang" -O2 -DNDEBUG --target=wasm32-wasi -fno-trapping-math -mthread-model single --sysroot="/opt/wasi-sdk/share/wasi-sysroot" -ID:/a/wasi-sdk/wasi-sdk/src/wasi-libc/libc-bottom-half/headers/private -ID:/a/wasi-sdk/wasi-sdk/src/wasi-libc/libc-bottom-half/cloudlibc/src/include -ID:/a/wasi-sdk/wasi-sdk/src/wasi-libc/libc-bottom-half/cloudlibc/src -c D:/a/wasi-sdk/wasi-sdk/src/wasi-libc/libc-bottom-half/crt/crt1.c -MD -MP && \
3796
mkdir -p "/opt/wasi-sdk/share/wasi-sysroot/lib/wasm32-wasi" && \
3797
mv *.o "/opt/wasi-sdk/share/wasi-sysroot/lib/wasm32-wasi"
3798
In file included from D:/a/wasi-sdk/wasi-sdk/src/wasi-libc/libc-bottom-half/crt/crt1.c:1:
3799
C:/Program Files/Git/opt/wasi-sdk/share/wasi-sysroot/include\wasi/api.h:27:10: fatal error: 'stddef.h' file not found
3800
#include <stddef.h>
3801
         ^~~~~~~~~~
3802
1 error generated.
3803
mingw32-make[1]: *** [Makefile:422: startup_files] Error 1
3804
mingw32-make[1]: Leaving directory 'D:/a/wasi-sdk/wasi-sdk/src/wasi-libc'
3805
mingw32-make: *** [Makefile:55: build/wasi-libc.BUILT] Error 2
3806
##[error]Process completed with exit code 1.
```

**Comment by sbc100** [comment]
maybe the cmake build would fix this stuff.   Do we have many ppl asking for windows support?

**Comment by pchickey** [comment]
My guess is the sysroot is being passed in wrong in the compiler-rt build, its pointing in /opt/wasi-sdk

**Comment by lygstate** [comment]
Windows CI already working, this can be closed

**Comment by sunfishcode** [comment]
Closing, per https://github.com/WebAssembly/wasi-sdk/pull/103#issuecomment-966320159.

**Comment by sunfishcode** [comment]
Closing, per https://github.com/WebAssembly/wasi-sdk/pull/103#issuecomment-966320159.

**Pull request closed without merging**
