### PR TITLE
Fix typos in Makefile

### PR DESCRIPTION
**Pull request by vnepogodin**
It breaks compilation of libcxxabi

### CODE REVIEW

**Review by sbc100 — APPROVED** [review]

**Comment by sunfishcode** [comment]
@lygstate The PR here is a seemingly simple fix, however the Windows CI is failing. Is this caused by #208?

**Comment by lygstate** [comment]
> @lygstate The PR here is a seemingly simple fix, however the Windows CI is failing. Is this caused by #208?

Let's me fix the CI, not caused by #208

**Comment by sunfishcode** [comment]
@vnepogodin The Windows and Docker issues are now fixed; would you mind rebasing this on current `main`?

**Comment by sunfishcode** [comment]
Thanks!

**Pull request merged**
