### PR TITLE
use llvm 12.0.0 release

### PR DESCRIPTION
**Pull request by pchickey**

### CODE REVIEW

**Review by sbc100 — APPROVED** [review]
Exciting!

**Comment by jedisct1** [comment]
> Exciting!

Not so much; it was tagged even though 13 known regressions since LLVM 11 are still open.

https://bugs.llvm.org/show_bug.cgi?id=48902
https://twitter.com/andy_kelley/status/1382443048571785216

I wouldn't rush.

**Comment by pchickey** [comment]
Of those regressions, it only looks like 2 of the regressions are miscompilations in InstCombine. I don't know for sure if those could affect wasm32-wasi. I'm inclined to go ahead and release on top of 12.0.0 unless @sbc100 can indicate that a 12.0.1 is coming shortly.

**Comment by sbc100** [comment]
In emscripten we have seen some regressions due to the new pass manager.. but I think we planning on simply accepting them.

**Comment by sbc100** [comment]
I'm not following the plans for a 12.0.1 release.

**Comment by pchickey** [comment]
Thanks. Sounds like we should just go ahead with a release based on 12.0.0 and do another release if or when patches come out.

**Pull request merged**
