### PR TITLE
Add tests for `clock`, `times`, and `getrusage`.

### PR DESCRIPTION
**Pull request by sunfishcode**
This is a basic test for https://github.com/WebAssembly/wasi-libc/pull/241.

### CODE REVIEW

**Comment by ricochet** [comment]
Should this update wasi-libc? That is usually in its own PR.

**Comment by sunfishcode** [comment]
> Should this update wasi-libc? That is usually in its own PR.

The update to wasi-libc is needed to pick up b9b64a695a35273f92574acc6270f0e059be3dca, which is needed to make these tests pass.

**Comment by sunfishcode** [comment]
Ah, it turns out that wasi-libc has already updated, so I've now dropped that change.

**Comment by sunfishcode** [comment]
This is just adding a few simple tests, so I think we can merge this.

**Pull request merged**
